notifications:
  email: false

os:
  - linux
  
language:
  - cpp
  
branches:
  only:
    - master
  
compiler:
  - gcc-5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - mpi-default-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-5" CC="gcc-5"; fi
  
script:
  - source build.sh
